### PR TITLE
Expose `wlroots` protocols + attempt to unify xml management

### PR DESCRIPTION
**Pull request by shegeley**

### CODE REVIEW

**Comment by Z572** [comment]
I think this is not a good idea, it would be better to have a search path for use-wayland-protocol.

**Comment by shegeley** [comment]
> I think this is not a good idea, it would be better to have a search path for use-wayland-protocol.
> 

Yes. I agree. It didn't come to my mind at the time. 

Do you mean using the Guix package `search-paths` option or something different?

**Comment by Z572** [comment]
like PATH environment variable, and must can build guile-wayland without guix, if people want pack to other distribution

**Comment by shegeley** [comment]
I understand that including whole Guix as a dependency is a bad idea in the release version. But the package is still heavily under development and Guix has a lot of really useful utils. So, I will use them at least for now. There should be some way to carefully export only the needed one from it and "forge" them into the needed package.

**Comment by shegeley** [comment]
I spent 2 days  trying to pack it properly using guix `search-path` but I can't make it work. Can't understand why.

**Comment by Z572** [comment]
see https://github.com/guile-wayland/guile-wayland/pull/9

**Comment by shegeley** [comment]
Figured out

**Comment by shegeley** [comment]
Please re-open

**Pull request closed without merging**
