### PR TITLE
Refactoring: project structure

### PR DESCRIPTION
**Pull request by shegeley**
Accomplishments:
1. Changed project structure:
  - Moved all `.c` code to `libguile-wayland`  and all `.scm` to `/modules` as in other `.scm` + `.c` projects (see `guile-ssh`, `guile-xosd` ...)
  - Partitioned makefiles accordingly 
2. Changed `guix.scm` and a way that load extension (coped from `guile-ssh`).  Now it can be build successfully with `guix build -f guix.scm`
3. `example/...` are now `....scm.in` and included in `configure.ac`

Problems: after build with `guix build -f guix.scm` I couldn't load `(bytestructure-class)` extension.

```
shegeley@zone51 ~/Projects/guile-wayland$ guix build -f guix.scm 
/gnu/store/5m4y8mfxdb4bsbmjy6gjxmkaqmbra8i3-guile-wayland-0.0.2
...
shegeley@zone51 /gnu/store/5m4y8mfxdb4bsbmjy6gjxmkaqmbra8i3-guile-wayland-0.0.2$ tree .
.
├── lib
│   ├── guile
│   │   └── 3.0
│   │       └── site-ccache
│   │           ├── wayland
│   │           │   ├── argument.go
│   │           │   ├── base.go
│   │           │   ├── client
│   │           │   │   ├── display.go
│   │           │   │   └── protocol
│   │           │   │       ├── wayland.go
│   │           │   │       └── xdg-shell.go
│   │           │   ├── config.go
│   │           │   ├── cursor.go
│   │           │   ├── egl.go
│   │           │   ├── event-loop.go
│   │           │   ├── interface.go
│   │           │   ├── list.go
│   │           │   ├── proxy.go
│   │           │   ├── scanner.go
│   │           │   ├── server
│   │           │   │   ├── client.go
│   │           │   │   ├── display.go
│   │           │   │   ├── global.go
│   │           │   │   ├── listener.go
│   │           │   │   ├── protocol
│   │           │   │   │   └── wayland.go
│   │           │   │   └── resource.go
│   │           │   ├── shm.go
│   │           │   ├── signal.go
│   │           │   └── util.go
│   │           └── wayland.go
│   ├── libguile-wayland.la
│   ├── libguile-wayland.so -> libguile-wayland.so.0.0.0
│   ├── libguile-wayland.so.0 -> libguile-wayland.so.0.0.0
│   └── libguile-wayland.so.0.0.0
└── share
    ├── doc
    │   └── guile-wayland-0.0.2
    │       └── COPYING
    └── guile
        └── site
            └── 3.0
                ├── wayland
                │   ├── argument.scm
                │   ├── base.scm
                │   ├── client
                │   │   ├── display.scm
                │   │   └── protocol
                │   │       ├── wayland.scm
                │   │       └── xdg-shell.scm
                │   ├── config.scm
                │   ├── cursor.scm
                │   ├── egl.scm
                │   ├── event-loop.scm
                │   ├── interface.scm
                │   ├── list.scm
                │   ├── proxy.scm
                │   ├── scanner.scm
                │   ├── server
                │   │   ├── client.scm
                │   │   ├── display.scm
                │   │   ├── global.scm
                │   │   ├── listener.scm
                │   │   ├── protocol
                │   │   │   └── wayland.scm
                │   │   └── resource.scm
                │   ├── shm.scm
                │   ├── signal.scm
                │   └── util.scm
                └── wayland.scm

21 directories, 51 files
shegeley@zone51 /gnu/store/5m4y8mfxdb4bsbmjy6gjxmkaqmbra8i3-guile-wayland-0.0.2$ guile -L share/guile/site/3.0/
GNU Guile 3.0.9
Copyright (C) 1995-2023 Free Software Foundation, Inc.

Guile comes with ABSOLUTELY NO WARRANTY; for details type `,show w'.
This program is free software, and you are welcome to redistribute it
under certain conditions; type `,show c' for details.

Enter `,help' for help.
scheme@(guile-user)> ,m (bytestructures guile)
scheme@(bytestructures guile)> ,b
cstring-pointer         #<variable 7f9f3008ab60 value: #<bytestructure-descriptor 0x7f9f2ffc30c0>>
scheme@(bytestructures guile)> ,m (wayland)
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling share/guile/site/3.0/wayland.scm
;;; compiling share/guile/site/3.0/wayland/config.scm
;;; compiled /home/shegeley/.cache/guile/ccache/3.0-LE-8-4.6/gnu/store/5m4y8mfxdb4bsbmjy6gjxmkaqmbra8i3-guile-wayland-0.0.2/share/guile/site/3.0/wayland/config.scm.go
;;; compiling share/guile/site/3.0/wayland/cursor.scm
;;; compiled /home/shegeley/.cache/guile/ccache/3.0-LE-8-4.6/gnu/store/5m4y8mfxdb4bsbmjy6gjxmkaqmbra8i3-guile-wayland-0.0.2/share/guile/site/3.0/wayland/cursor.scm.go
;;; compiling share/guile/site/3.0/wayland/egl.scm
;;; compiled /home/shegeley/.cache/guile/ccache/3.0-LE-8-4.6/gnu/store/5m4y8mfxdb4bsbmjy6gjxmkaqmbra8i3-guile-wayland-0.0.2/share/guile/site/3.0/wayland/egl.scm.go
;;; compiling share/guile/site/3.0/wayland/event-loop.scm
;;; compiling share/guile/site/3.0/wayland/base.scm
;;; WARNING: compilation of share/guile/site/3.0/wayland/base.scm failed:
;;; no code for module (bytestructure-class)
;;; WARNING: compilation of share/guile/site/3.0/wayland/event-loop.scm failed:
;;; no code for module (bytestructure-class)
;;; compiling share/guile/site/3.0/wayland/util.scm
;;; WARNING: compilation of share/guile/site/3.0/wayland/util.scm failed:
;;; no code for module (bytestructure-class)
;;; WARNING: compilation of share/guile/site/3.0/wayland.scm failed:
;;; no code for module (bytestructure-class)
;;; compiling share/guile/site/3.0/wayland/interface.scm
;;; WARNING: compilation of share/guile/site/3.0/wayland/interface.scm failed:
;;; no code for module (bytestructure-class)
While executing meta-command:
no code for module (bytestructure-class)
```

### CODE REVIEW

**Comment by Z572** [comment]
push at 08a5b82e97fe04d1b16515a0b864559056ccbbfc , 
and change some:
- guix.scm phase no end with `#t`
- Makefile.am build libguile-wayland before modules/wayland
- pre-inst-env.in not `$(abs_top_builddir)`, just $abs_top_builddir
- examples add `--no-auto-compile -e main` at head
- configure.ac `chmod +x` for exampels.

> Problems: after build with guix build -f guix.scm I couldn't load (bytestructure-class) extension.

because it is propagated-inputs, so just use `guix shell guile -f guix.scm -- guile` , guix will add guile-bytestructure-class to profile,and then you can use `,use (wayland)`.

**Comment by Z572** [comment]
`(bytestructures guile)` beacuse `guix` propagated guile-git , guile-git propagated guile-bytestructures

**Comment by shegeley** [comment]
Excuse me. I didn't «get and change some...». Would you like me to change all the listed back? 

> Makefile.am build libguile-wayland before modules/wayland


Yes. It is how it works in some other modules I saw (`guile-ssh`, `guile-xosd`). First the build `libguile-x.la` and then uses it in `modules`

**Comment by shegeley** [comment]
```
shegeley@zone51 ~/Projects/guile-wayland$ guix shell guile -f guix.scm -- guile
The following derivation will be built:
  /gnu/store/3cwlzmkjaapfzn5hjrxz9k3dx40sijf7-profile.drv

building CA certificate bundle...
listing Emacs sub-directories...
building fonts directory...
building directory of Info manuals...
building profile with 2 packages...
GNU Guile 3.0.9
Copyright (C) 1995-2023 Free Software Foundation, Inc.

Guile comes with ABSOLUTELY NO WARRANTY; for details type `,show w'.
This program is free software, and you are welcome to redistribute it
under certain conditions; type `,show c' for details.

Enter `,help' for help.
scheme@(guile-user)> ,m (wayland)
While executing meta-command:
no code for module (bytestructure-class)
```

**Comment by shegeley** [comment]
Are you sure that `(bytestructure-class)` is packed properly?  
On the latest master (with `propagated-inputs`) I get 
```
shegeley@zone51 ~/Projects/guile-wayland$ guix shell guile -f guix.scm -- guile
GNU Guile 3.0.9
Copyright (C) 1995-2023 Free Software Foundation, Inc.

Guile comes with ABSOLUTELY NO WARRANTY; for details type `,show w'.
This program is free software, and you are welcome to redistribute it
under certain conditions; type `,show c' for details.

Enter `,help' for help.
scheme@(guile-user)> ,m (wayland)
While executing meta-command:
no code for module (bytestructure-class)
```

**Comment by Z572** [comment]
> I didn't get and change some.... Would you like me to change all the listed back?

no, I added these changes at commit time.

**Comment by Z572** [comment]
emm, it works for me, maybe need `guix shell guile -f guix.scm --rebuild-cache -- guile`？ 
图片

**Comment by shegeley** [comment]
> `guix shell guile -f guix.scm --rebuild-cache -- guile`

Absolutely. Thanks a lot. The problem was in cache.

**Pull request closed without merging**
